import "@/styles/globals.css";
import { ProgramProvider } from "../contexts/programContext";
import App from "next/app";
import { FormDataProvider } from "@/contexts/bookingContext";
import Head from "next/head";
import NavBar from "@/components/NavnBar";
import { useEffect } from "react";

// import { LocalizationProvider } from "@mui/x-date-pickers";
// import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";

export default function MyApp({ Component, pageProps }) {
  useEffect(() => {
    document.body.className = pageProps.isLanding ? "landing-background" : "program-background";
  });
  return (
    <>
      {/* <Head>
        <title>Foo Festival</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://use.typekit.net/bxq7sds.css" />
      </Head> */}
      <NavBar />
      <ProgramProvider>
        <FormDataProvider>
          {/* <BookFormProvider> */}
          <Component {...pageProps} />;{/* </BookFormProvider> */}
        </FormDataProvider>
      </ProgramProvider>
    </>
  );
}
