import { Html, Head } from "next/document";

export default function Document() {
  return (
    <Html>
      <Head>
        <title>Foo Festival</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://use.typekit.net/bxq7sds.css" />
        <link rel="icon" href="" />
      </Head>
    </Html>
  );
}
